\hypertarget{classsubprocess_1_1OSError}{}\section{subprocess\+:\+:O\+S\+Error Class Reference}
\label{classsubprocess_1_1OSError}\index{subprocess\+::\+O\+S\+Error@{subprocess\+::\+O\+S\+Error}}


{\ttfamily \#include $<$subprocess.\+hpp$>$}



Inheritance diagram for subprocess\+:\+:O\+S\+Error\+:
% FIG 0


Collaboration diagram for subprocess\+:\+:O\+S\+Error\+:
% FIG 1
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classsubprocess_1_1OSError_ac2b4771e9abb7390ac61a7e1d31d1ca1}\label{classsubprocess_1_1OSError_ac2b4771e9abb7390ac61a7e1d31d1ca1}} 
{\bfseries O\+S\+Error} (const std\+::string \&err\+\_\+msg, int err\+\_\+code)
\end{DoxyCompactItemize}


\subsection{Detailed Description}
class\+: \hyperlink{classsubprocess_1_1OSError}{O\+S\+Error} Thrown when some system call fails to execute or give result. The exception message contains the name of the failed system call with the stringisized errno code. Check \hyperlink{classsubprocess_1_1Popen}{Popen} class A\+PI\textquotesingle{}s to know when this exception would be thrown. Its usual that the A\+PI exception specification would have this exception together with \hyperlink{classsubprocess_1_1CalledProcessError}{Called\+Process\+Error}. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
subprocess.\+hpp\end{DoxyCompactItemize}
